stages:
  - rpm-package
  - local-test
  - distributed-test
  - documentation
  - rpm-stable

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'
  except:
    - master

static-analysis:
  stage: local-test
  tags:
    - docker
  script:
    - 'static-analysis.sh'
  allow_failure: true
  except:
    - master

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

unit-test-python27:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh'
  except:
    - master

unit-test-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh python36'
  except:
    - master

coverage-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'coverage-virtualenv.sh python36'
  coverage: '/TOTAL.*\s+(\d+%)$/'
  allow_failure: false
  except:
    - master

e2e-localhost-siptools-research:
  stage: local-test
  script:
    - 'e2e-fairdata-localhost.sh dpres-research-rest-api'
  except:
    - develop
    - master
    - tags

e2e-distributed-siptools-research:
  stage: distributed-test
  tags:
    - pouta-gitlab-runner1
  script:
    - 'e2e-fairdata.sh dpres-research-rest-api e2e-distributed'
  only:
    - develop
    - tags

rpm-stable:
  stage: rpm-stable
  script:
    - 'rpm-stable.sh'
  only:
    - tags

documentation:
  stage: documentation
  script:
    - 'documentation.sh'
  only:
    - develop
