stages:
  - rpm-package
  - local-test

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

e2e-localhost-metax-access:
  stage: local-test
  script:
    - 'e2e-fairdata.sh dpres-research-rest-api'
  except:
    - master
