---
stages:
  - rpm-package
  - local-test
  - documentation

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

unit-test-python27:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh'
  except:
    - master

unit-test-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh python36'
  except:
    - master

e2e-localhost-metax-access:
  stage: local-test
  script:
    - 'e2e-fairdata-localhost.sh dpres-research-rest-api'
  except:
    - master

documentation:
  stage: documentation
  script:
    - 'documentation.sh'
  only:
    - develop
