"""Expose public interface from submodules."""
from .error import (  # noqa: F401
    ContractNotAvailableError, DataciteGenerationError,
    DatasetNotAvailableError, DirectoryNotAvailableError,
    FileNotAvailableError, MetaxError,
    ResourceAlreadyExistsError, ResourceNotAvailableError)

DS_STATE_NONE = -1  # Default in Metax V3
DS_STATE_INITIALIZED = 0
DS_STATE_GENERATING_METADATA = 10
DS_STATE_TECHNICAL_METADATA_GENERATED = 20
DS_STATE_TECHNICAL_METADATA_GENERATION_FAILED = 30
DS_STATE_INVALID_METADATA = 40
DS_STATE_METADATA_VALIDATION_FAILED = 50
DS_STATE_VALIDATED_METADATA_UPDATED = 60
DS_STATE_VALIDATING_METADATA = 65
DS_STATE_REJECTED_BY_USER = 70
DS_STATE_METADATA_CONFIRMED = 75
DS_STATE_ACCEPTED_TO_DIGITAL_PRESERVATION = 80
DS_STATE_IN_PACKAGING_SERVICE = 90
DS_STATE_PACKAGING_FAILED = 100
DS_STATE_SIP_SENT_TO_INGESTION_IN_DPRES_SERVICE = 110
DS_STATE_IN_DIGITAL_PRESERVATION = 120
DS_STATE_REJECTED_IN_DIGITAL_PRESERVATION_SERVICE = 130
DS_STATE_IN_DISSEMINATION = 140

DS_STATE_ALL_STATES = (
    DS_STATE_NONE,
    DS_STATE_INITIALIZED,
    DS_STATE_GENERATING_METADATA,
    DS_STATE_TECHNICAL_METADATA_GENERATED,
    DS_STATE_TECHNICAL_METADATA_GENERATION_FAILED,
    DS_STATE_INVALID_METADATA,
    DS_STATE_METADATA_VALIDATION_FAILED,
    DS_STATE_VALIDATED_METADATA_UPDATED,
    DS_STATE_VALIDATING_METADATA,
    DS_STATE_REJECTED_BY_USER,
    DS_STATE_METADATA_CONFIRMED,
    DS_STATE_ACCEPTED_TO_DIGITAL_PRESERVATION,
    DS_STATE_IN_PACKAGING_SERVICE,
    DS_STATE_PACKAGING_FAILED,
    DS_STATE_SIP_SENT_TO_INGESTION_IN_DPRES_SERVICE,
    DS_STATE_IN_DIGITAL_PRESERVATION,
    DS_STATE_REJECTED_IN_DIGITAL_PRESERVATION_SERVICE,
    DS_STATE_IN_DISSEMINATION,
)
from .metax import Metax  # noqa: F401, E402
